### ISSUE TITLE
Kill counts stopped being displayed.

### ISSUE THREAD

**Issue by enzomartins** [ChalkPE/ffxiv-kill-counter#28]
![image](https://user-images.githubusercontent.com/45863649/176929929-6ca8c246-5033-4ddf-9475-72db2e18dac4.png)
The overlay only worked for the first enemy I killed. After that, it stopped updating. I've tried reloading the overlay, reinstalling it, forcing white background and clicking the "reload arrow icon", but none of those could make it work again.

**Comment by amasover** [comment]
Same here, though I am not on Korean server.

**Comment by chalkpe** [comment]
https://github.com/chalkpe/ffxiv-kill-counter/commit/3ee950ecb432874b25926099395b468980960c62 now overlay supports global server, may fix this issue.

![image](https://github.com/chalkpe/ffxiv-kill-counter/assets/9481405/71870fb5-3a11-45db-a609-5db165b47d5e)
![image](https://github.com/chalkpe/ffxiv-kill-counter/assets/9481405/185d228a-56e2-4f3b-82b2-9165ee012ac6)
